services:
  server:
    container_name: amazonia-minada-back
    restart: always
    build:
      context: .
      args:
        - NODE_ENV=production
        - TZ=America/Sao_Paulo
    working_dir: /usr/app
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_ADDRESS: ${MONGO_DB_ADDRESS}
      NODE_ENV: production
      TZ: America/Sao_Paulo