version: '2'

services:
  server:
    restart: always
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env

  database:
    image: mongo
    volumes:
      - dbdata:/data
    ports:
      - 27017:27017
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo

volumes:
  dbdata: